spring:
  profiles:
    active: local
    include: properties
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5
      pool-name: HikariCP-POOL
      max-lifetime: 180000
      connection-timeout: 30000
  jpa:
    hibernate:
      connection:
        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    properties:
      hibernate:
        default_schema: public
        show_sql: false
        format_sql: true
        use_sql: true
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
    devtools:
      restart:
        enabled: false
      livereload:
        enabled: true
    main:
      allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google #Oauth2 라이브러리를 사용한다면 고정 URI
            client-id: 49125488226-omd7fa2inu9h54fk2607h89224u4rhrc.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver #Oauth2 라이브러리를 사용한다면 고정 URI
            client-id: FlNGLJthlKJpcdy8Jd8S
            client-secret: oX1kpXf04x
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보 데이터 Key (JSON)